ZLShengXian/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.urls import path, include
from myapps import orderapp,userapp,productapp

urlpatterns = [

    url(r'admin/', admin.site.urls),
    url(r'^order/',include('orderapp.urls')),
    url(r'^user/',include('userapp.urls')),
    url(r'^sy/',include('productapp.urls')),

]

myapps/orderapp/models.py
from django.db import models
from userapp.models import User,Address
from productapp.models import Products

# Create your models here.

#购物车
class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)  #用户
    products = models.ForeignKey(Products,on_delete=models.CASCADE)  #购买商品

    #数量
    cnt = models.IntegerField(default=1)
    #是否被选择，提交订单时使用
    isSelected = models.BooleanField(default=True)

    class Meta:
        db_table = 'sx_cart'


#订单
class Order(models.Model):
    #单号
    orderNum = models.CharField(primary_key=True,max_length=50,verbose_name='订单号')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    #订单收货地址
    order_address = models.ForeignKey(Address,on_delete=models.SET_NULL,null=True)

    #订单总金额
    orderPrice = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    #支付状态
    pay_state = (
        (0,'待支付'),
        (1,'已支付'),
        (2,'已退款'),
    )

    payState = models.IntegerField(choices=pay_state,default=0)

    #支付方式
    pay_types = (
        (0,'余额'),
        (1,'支付宝'),
        (2,'微信')
    )
    payType = models.IntegerField(choices=pay_types,default=0)

    #订单状态
    order_state = (
        (0,'待支付'),
        (1,'待收货'),
        (2,'待评价'),
        (3,'已评价'),
        (4,'已取消')
    )
    orderState = models.IntegerField(choices=order_state,default=0)

    @property
    def payStateName(self):
        return self.pay_state[self.payState][1]

    @property
    def payTypeName(self):
        return self.pay_types[self.payType][1]

    @property
    def orderStateName(self):
        return self.order_state[self.orderState][1]

    #下订单时间
    orderTime = models.DateTimeField(auto_now_add=True)

    #订单信息最后一次修改时间
    orderChangeTime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'sx_order'


#订单明细
class OrderGoods(models.Model):
    #订单
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    #商品
    products = models.ForeignKey(Products,on_delete=models.SET_NULL,null=True)
    #商品数量
    cnt = models.IntegerField(default=1)
    #商品小计
    sumprice = models.DecimalField(max_digits=10,decimal_places=2,default=0,verbose_name='某种商品的总价')

    class Meta:
        db_table = 'sx_ordergoods'

templates/address.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>我的收货地址</title>
    <link rel="stylesheet" type="text/css" href="/static/address/css/address.css">
    <link href="/static/address/css/msgbox.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/static/user/main/css/bootstrap.min.css">

    <script type="text/javascript" language="javascript" src="/static/address/js/jquery.js"></script>
    <script type="text/javascript" language="javascript" src="/static/address/js/jquery.form.js"></script>
    <script type="text/javascript" language="javascript" src="/static/address/js/jquery-impromptu.1.3.js"></script>
    <script type="text/javascript" language="javascript">
      var frontPath="";
    </script>
    <script type="text/javascript" language="javascript" src="/static/address/js/address.js"></script>
  </head>
  <body>
    <div class="usercenter_address">
    	<h2 class="header"><span></span>收货地址</h2>
        <ul class="content">


            {% for myAddr in myAddrs %}
                {% if myAddr.isselect == 1 %}
                    <li id="defalutAddress" class="adds old_add_default"></li>
                    <input type="hidden" value="20868010" id="defalutAddressId">

                    <li class="adds old_add" id="old_add_20868010">
                        <div class="name_infor">
                            <div class="name_etc" style="width: 240px">
                            <span class="name"
                                  title="{{ myAddr.name }}">{{ myAddr.name }}…</span><span>收</span><span>{{ myAddr.phone }}</span>
                                <span class="default_add">默认地址</span>
                            </div>
                            <ul class="btns" style="width: 150px">
                                <li class="delete"><a class="delete1">删除</a></li>
                                <li class="edit"><a class="change1">编辑</a></li>
                                <li class="set_default"><a href="javascript:"
                                                           onclick="updateDefaultAddress({{ myAddr.zipCode }},{{ myAddr.name }},{{ myAddr.detailAddr }},{{ myAddr.phone }});">设为默认</a>
                                </li>
                            </ul>
                        </div>
                        <div class="add_infor">
                            <strong class="add_city"><span>{{ myAddr.detailAddr }}</span></strong>

                        </div>
                    </li>
                {% else %}

                    <li class="adds old_add" id="old_add_20868118">
                        <div class="name_infor">
                            <div class="name_etc">
                                <span class="name"
                                      title="{{ myAddr.name }}">{{ myAddr.name }}…</span><span>收</span><span>{{ myAddr.phone }}</span>
                                <span class="default_add">默认地址</span>
                            </div>
                            <ul class="btns">
                                <li class="delete"><a class="delete1">删除</a>
                                </li>
                                <li class="edit"><a class="change1">编辑</a></li>
                                <li class="set_default"><a href="javascript:"
                                                           onclick="updateDefaultAddress({{ myAddr.zipCode }},{{ myAddr.name }},{{ myAddr.detailAddr }},{{ myAddr.phone }});">设为默认</a>
                                </li>
                            </ul>
                        </div>
                        <div class="add_infor">
                            <strong class="add_city"><span>{{ myAddr.detailAddr }}</span></strong>


                        </div>
                    </li>
                {% endif %}

            {% endfor %}





         <li class="addnew_add">
             <ul>
                 <li class="addpic"></li>
                 <li class="addnew_text">添加新地址</li>
                 <!-- <li class="left_num">还可创建16个</li> -->
             </ul>
         </li>

        </ul>

        <div class="modal" id="myModal" style="margin-top: -4rem" tabindex="-1" role="dialog"
             aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModalLabel" style="font-weight: bold">添加新地址</h4>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="recipient-name" class="control-label"
                                       style="font-weight: normal;font-size: 0.4rem">收货人</label>
                                <input type="text" class="form-control" id="recipient-name" name="name">
                            </div>
                            <div class="form-group">
                                <label for="recipient-phone" class="control-label"
                                       style="font-weight: normal;font-size: 0.4rem">联系电话</label>
                                <input type="text" class="form-control" id="recipient-phone" name="phone">
                            </div>
                            <div class="form-group">
                                <label for="recipient-address" class="control-label"
                                       style="font-weight: normal;font-size: 0.4rem">收货地址</label>
                                <input type="text" class="form-control" id="recipient-address" name="address">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button id="save" type="button" class="btn btn-sm btn-primary">保存收货地址</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
    <div id="addDIV"></div>     <!-- 添加页面 -->
    <div id="updateDIV"></div>  <!-- 修改页面 -->
  </body>
  </html>

templates/allorder.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>我的订单</title>
    <link rel="stylesheet" type="text/css" href="/static/myorder/css/modal.css"/>

    <link rel="stylesheet" type="text/css" href="/static/myorder/css/base.css"/>
    <link rel="stylesheet" type="text/css" href="/static/myorder/css/common.css"/>
    <link rel="stylesheet" type="text/css" href="/static/myorder/css/commonalert.css"/>
    <link rel="stylesheet" type="text/css" href="/static/myorder/css/ll.ui.datepicker.1.0.0.css"/>
    <link rel="stylesheet" type="text/css" href="/static/myorder/css/new_sell_list.css"/>
    <link rel="stylesheet" type="text/css" href="/static/myorder/css/conqu_order.css"/>
    <link rel="stylesheet" type="text/css" href="/static/myorder/css/live800button.css"/>
    <script type="text/javascript" language="javascript" src="/static/main/js/jquery.min.js"></script>
    <script type="text/javascript" language="javascript" src="/static/main/js/bootstrap.min.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/addtocartmessage.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/ll.ui.datepicker.1.0.0.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/sny1.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/order_common.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/new_order_sell_list.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/engine.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/util.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/orderpayservice.js"></script>
    <script type="text/javascript" language="javascript" src="/static/myorder/js/allorder.js"></script>
    <script type="text/javascript" src="/static/myorder/js/commonalert.js"></script>

    <script type="text/javascript" language="javascript" src="/static/myorder/js/live800button.js" charset="utf-8"></script>
</head>
<body>
{#<form action="/Member/menumyorderlist.do" id="myOrderListForm" method="get">#}
{#    <input id="mid" name="mid" type="hidden" value="0"/>#}
{#    <input id="ColumnId" name="ColumnId" type="hidden" value=""/>#}
{#    <input id="orderType" name="orderType" type="hidden" value="8"/>#}
{#    <input id="limitStates" name="limitStates" type="hidden" value="1"/>#}
{#    <input id="state" name="state" type="hidden" value="101"/>#}
{#    <input id="page" name="page" type="hidden" value="1"/>#}
{#    <input id="isSignfor" name="isSignfor" type="hidden" value="0"/>#}
{#    <input id="tag" name="tag" type="hidden" value="5"/>#}
{#    <input id="aliasCode" name="aliasCode" type="hidden" value=""/>#}
{#    <input id="beginDate" name="beginDate" type="hidden" value=""/>#}
{#    <input id="endDate" name="endDate" type="hidden" value=""/>#}
{#    <input id="orderStateValue" name="orderStateValue" type="hidden" value="订单状态"/>#}
{#    <input id="isHaveSearch" name="isHaveSearch" type="hidden" value="0"/>#}
{#    <input id="isSolr" name="isSolr" type="hidden" value="y"/>#}
{#    <input id="mzhOrderCount" name="mzhOrderCount" type="hidden" value="0"/>#}
{#    <input id="ttmenumyorderlist" name="tt" type="hidden" value="0.5350400116339185"/>#}
{#</form>#}
<input id="j-cancel-orderid" type="hidden" value=""/>
<input id="j-cancel-orderaliasid" type="hidden" value=""/>
<input id="j-cancel-flag" type="hidden" value=""/>
<div id="gotopay" style="display: none;"></div>

<div class="wrap_list">


    <div class="list_1f"><b></b>我的订单</div>

    <div class="list_2f">

        <div class="l2f_1f">


            <div id="tabDiv" class="l2f_1f_left">
                <ul>
                    <li>
                        <div class="{% if state == '0' %}
                        active
                        {% endif %}"><a href="/order/allorder/0">全部订单</a></div>
                    </li>
                    <li>
                        <div class="{% if state == '1' %}
                        active
                        {% endif %}"><a href="/order/allorder/1">待付款</a></div>
                    </li>
                    <li>
                        <div class="{% if state == '2' %}
                        active
                        {% endif %}"><a href="/order/allorder/2">待收货</a></div>
                    </li>
                    <li>
                        <div class="{% if state == '3' %}
                        active
                        {% endif %}"><a href="/order/allorder/3">待评价</a></div>
                    </li>
                    <li>
                        <div class="{% if state == '4' %}
                        active
                        {% endif %}"><a href="/order/allorder/4">交易完成</a></div>
                    </li>


                </ul>
            </div>
        </div>

        <div class="l2f_2f"></div>
        <div class="l2f_2fin">
            <ul>
                <li class="w291">商品</li>
                <li class="w83">数量</li>
                <li class="w128">订单金额</li>
                <li class="w78">订单状态</li>
                <li class="w106">操作</li>
                <div class="clear"></div>
            </ul>
        </div>

        {% for order in orders %}
              <div class="div_popup" style="display:block;">
            <div class="l2f_3f">
                <div class="l2f_3f_title">
                    <ul class="l2f_3f_title_ul">
                        <li class="title_li01">订单编号：
                            <a target="_blank" id=""
                               href="/order/toorder/{{ order.orderNum }}">
                                <span> {{ order.orderNum }}</span>
                            </a>
                        </li>
                        <li class="title_li02">下单时间：
                            {{ order.orderTime }}
                        </li>
                        <li class="title_li03" style="margin-left: 90px;color: red">
                            <strong>￥{{ order.orderPrice }}</strong>
                        </li>
                    </ul>
                </div>
                <div class="l2f_3f_detail">

                    <div class="fl detail_left">

                        {% for ordpro in order.ordergoods_set.all %}
                            <ul>
                            <li class="w291">
                                <dl class="dl2">
                                    <dt>
                                        {# 商品图片 #}
                                        <span>
                                            <img title="{{ pro.products.productname }}"
                                                 src="{{ ordpro.products.productimg }}"/>
                                        </span>
                                    </dt>
                                    {# 商品名 #}
                                    <dd><span>{{ ordpro.products.productname|truncatechars:60 }}</span></dd>
                                </dl>
                            </li>
                            <li class="w83">X&nbsp;{{ ordpro.cnt }}</li>
                        </ul>
                        {% endfor %}

                    </div>
                    <ul class="fl detail_right">
                        <li class="w128 jh01">
                            <div class="outer jh01">
                                <div class="middle">
                                    <div class="inner">
                                        <p>合计：
                                            <span class="c_red">{{ order.orderPrice }}</span>
                                        </p>
                                        {% if order.payState == 1 %}
                                            <p>支付方式： {{ order.payTypeName }}</p>
                                        {% endif %}

                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="w78 jh02">
                            <div class="outer jh01">
                                <div class="middle">
                                    <div class="inner">
                                        <p class="color_01" id="orderstate">
                                            {{ order.orderStateName }}  {# 订单状态 #}
                                        </p>
                                        <div class="list_time">


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="w106 topaybtn jh03" style="z-index: 99;">
                            <div class="outer jh01">
                                <div class="middle">
                                    <div class="inner">

                                        <div id="cancelbtn_0">
                                            {# 未支付的情况 #}
                                            {% if order.payState == 0 and order.orderState == 0 %}
                                            <span id="canceltopay" class="topayimg">
                                                <a href="/order/toorder/{{ order.orderNum }}" target="_blank"><p class="font_white forpay" id="topay">去支付</p></a>
                                            </span>
                                            <a class="offorder" id="{{ order.orderNum }}" style="cursor: pointer">取消订单</a>
                                            {% else %}
                                                <a  class="offorder" id="{{ order.orderNum }}" style="cursor: pointer">删除订单</a>
                                            {% endif %}

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </li>
                        <div class="clear"></div>
                    </ul>
                    <div class="clear"></div>

                </div>
            </div>
        </div>
        {% endfor %}

        <div class="pglist_page">
            <div class='page'>
                <div class='page_l'><a href='#' class='prev' title='目前已是第一页'>上一页</a><a class='select'>1</a><a
                        class='next' title='目前已是最后一页'>下一页</a></div>
                <div class='page_m'>共<span>1</span>页</div>
                <div class='page_m_2'>到第</div>
                <div class='page_m_3'><input type='text' class='page_input' value='1'></div>
                <div class='page_m_4'>页</div>
                <div class='page_r'><input
                        type='button'></div>
            </div>
        </div>


    </div>

</div>

<input type="hidden" id="theorderId"/>

{# 删除模态框 #}
<div class="modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document" style="margin: 180px auto">
<div class="modal-content" style="margin: 0 120px">
  <div class="modal-body">
    <h3><strong><span id="delMsg"></span></strong></h3>
  </div>
  <div class="modal-footer">
    <button type="button" id="close" class="btn btn-sm btn-default" data-dismiss="modal">关闭</button>
      <button id="ok" type="button" class="btn btn-sm btn-default">确定</button>
  </div>
</div>
</div>
</div>


</body>
</html>

templates/toorder.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>订单支付_中粮我买网</title>
    <link rel="stylesheet" type="text/css" href="/static/main/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/cart/css/checkoutcommon.css"/>
    <link rel="stylesheet" type="text/css" href="/static/cart/css/common.css"/>
    <link rel="stylesheet" type="text/css" href="/static/cart/css/cart.css"/>
    <script type="text/javascript" src="/static/main/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/main/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/main/js/swiper.min.js"></script>
    <script type="text/javascript" src="/static/cart/js/toorder.js"></script>

</head>
<body>
<div class="cart_content">
    <div id="header" class="m">
        <div class="w">
            <ul class="fr">
                <li class="myaccount" id="myaccount" data-first="y">
                    <a href="/order/myhome/0" class="ian white">我的账户</a><i></i><i
                        class="accountpng" id="topaccountpng" style="display:none"></i>
                    <div id="myaccount_cont" class="myaccount_cont loadding"></div>
                </li>
            </ul>
            <ul class="fr" id="top_login_span">
                <li class='none'><span class='nickname'>哈拉嘿呦</span></li>
                <li class='none'><a href='/Member/Exit.do?mid=0'>退出</a></li>
            </ul>
        </div>
    </div>
    <div class="header_div w">
        <div class="logo_a"><a href='http://www.womai.com' target='_blank'><img data-order="100"
                                                                                src='/static/cart/picture/2018042510164955.png'
                                                                                width='210' height='80' alt='返回首页'
                                                                                border='0'/></a></div>

    </div>
    <script type="text/javascript" src="/static/cart/js/commonalert.js"></script>
    <link type="text/css" rel="StyleSheet" href="/static/cart/css/commonalert.css"/>


    <div class="trip_div" style="height: 90px">
        <div class="trip_content"><span class="tc_left">订单支付</span></div>
        <div class="clear"></div>
        <div class="delivery-tip fl">
            <div class="delivery-tit fl">
                <strong>收件人</strong>：<span class="address">{{ order.order_address.name }}</span>
                <strong>&nbsp;&nbsp;收货地址</strong>：<span class="address">{{ order.order_address.detailAddr }}</span>
                <strong>&nbsp;&nbsp;联系电话</strong>：<span class="address">{{ order.order_address.phone }}</span>
            </div>
            <div id="loadRegion" class="addr_select fl"></div>
            <div class="clear"></div>
        </div>

        <div class="clear"></div>
    </div>
    <div class="shopping_cart">
        <div class="order_nav">
            <ul class="fl">
                <li data-curtab="1" data-tab="1" data-index="1" data-cartids="1" data-mid="0" class="hover_li">我买网发货单</li>
            </ul>
            <div id="j-totalwithdeliveryrule" class="fr"></div>
            <div class="clear"></div>
        </div>
        <div class="order_contents">

            <div class="ordercont_titleline">
                <div class="odct_title ordercon_title1">商品</div>
                <div class="odct_title ordercon_title2">单价</div>
                <div class="odct_title ordercon_title3">数量</div>
                <div class="odct_title ordercon_title5" style="width: 150px">小计</div>
                <div class="clear"></div>
            </div>
            <div class="ordercont_content" data-first="n" style="display:block">
             <div id="loadshowcart1">


                    <input id="j-relationFreeConfig1" type="hidden" data-mid="0" data-type="2" data-sellerid="0"
                           value=""/>


                    <div class="ordercont_content_cw">


                        <div class="coupontip">

                        </div>



                        <div class="ordercont-cw-con">
                            {# 根据订单取出所有订单商品 #}
                            {% for pro in order.ordergoods_set.all %}
                                       {# 订单信息 #}
                            <div class="content_type content_type1 content_type_zp">

                                <div class="ct1 contype1_cont1 ct_zp">
                                    <div>

                                        <a href=""
                                           class="img_a">
                                            <img src="{{ pro.products.productimg }}"/>  {# 商品图片 #}
                                        </a>
                                        <div class="contype1_cont1_cent fl">
                                            <span style="color: black">{# 名字 #}
                                                {{ pro.products.productname|truncatechars:60 }}
                                            </span>
                                            <div class="sevendays-preference">
                                                <div class="clear"></div>
                                            </div>



                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <div class="ct1 contype1_cont2" id="price_{{ cart.id }}" style="width: 130px">
                                    {{ pro.products.price }}{# 购物车价格 #}
                                </div>
                                <div class="ct1 contype1_cont3" style="width:140px; padding: 32px 0 0 3px;">
                                    <div class="input_goods" id="input_goods_1_0_616969" style="width: 70px">
                                        <span>{{ pro.cnt }}</span>
                                    </div>
                                </div>
                                <div class="ct1 contype1_cont5">￥<span id="sumpro_{{ pro.id }}" >{{ pro.sumprice }}</span></div>


                                <div class="clear"></div>
                            </div>
                            {% endfor %}
                                    <div class="cont j-relationFree1 relationFree" id="j-relationFree1"></div>
                           </div>

                            </div>

                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="order_amount">
                        <div class="fl">



                            <div class="oal_img"></div>

                            <div></div>


                        </div>
                        <div class="ordam-total">
                                {% if order.payState == 0 %}
                                <span class="oar_title-total fl" style="font-size: 20px;font-family: bold;color: red">应付金额：{{ order.orderPrice|floatformat:2 }}</span>
                                <div class="clear"></div>
                                {% endif %}
                            </div>
                            <div style="margin: 20px 0 0 0 ">
                                {% if order.payState == 0 %}
                                <span class="oar_title-total fl" style="font-size: 18px;font-family: bold">请选择支付方式</span>
                                <br/>
                                {% endif %}
                                <div id="payBtn" style="margin: 20px 0 80px 0 " order_id="{{ order.orderNum }}">
                                {% if order.payState == 0 %}
                                    <button id="0" class="btn btn-warning" style="width: 120px">余额</button>
                                    <button id="1" class="btn btn-primary" style="width: 120px;margin-left: 20px">支付宝</button>
                                    <button id="2" class="btn btn-success" style="width: 120px;margin-left: 20px">微信</button>
                                {% elif order.payState == 1 %}
                                    <span class="btn btn-success" style="width: 240px;height: 40px;font-family: bold;font-size: 16px"><span>此订单已支付</span>
                                    <span>支付方式：</span><span style="color: black">{{ order.payTypeName }}</span></span>
                                {% else %}
                                    <span>此订单已退款</span>
                                {% endif %}

                                <div>
                                <div class="clear"></div>
                            </div>


                        <div class="clear"></div>
                    </div>

                    <div class="goods_list" style="display: none">
                        <div class="golist_title" >
                            <ul>
                                <li class="recommendlike 14 false" style="display: none">猜你喜欢</li>
                                <li class="current lastfavor" style="display: none">最近收藏</li>

                                <div class="clear"></div>
                            </ul>
                        </div>
                        <div class="golist_all"></div>
                    </div>



                </div>

            </div>

        </div>
    </div>
</div>


{# 支付模态框 #}
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document" style="margin: 180px auto">
    <div class="modal-content" style="margin: 0 100px">
      <div class="modal-body">
        <h3><strong><span id="payMsg">正在支付...</span></strong></h3>
      </div>
    </div>
  </div>
</div>

<link rel="stylesheet" type="text/css" href="/static/cart/css/simplebottom.css"/>
<div class="success-footer w">
    <p>
        <div class="beian">
            <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010102000458">

                <img src="/static/cart/picture/beian.png"/>
    <p style="color:#606060;">京公网安备 11010102000458号</p>
    </a>
</div>
<span>|</span> 京ICP备 13003995号 <span>|</span> 营业执照（统一社会信用代码）91110000055590239L <span>|</span>
食品经营许可证：JY11105020028185</p>
<p class="copyright">Copyright&#169;2009-2018 womai.com.hk 版权所有</p>
</div>

<img src=""
     style="display:none;width:0;height:0;margin:0;padding:0;border:0;">



</body>
</html>